/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OOPDB;

import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.lang.Object;

public class CRUD extends javax.swing.JFrame {

    
    public CRUD() {
        initComponents();
        connect();
    }
    Connection condb ;
    PreparedStatement pst ;
    ResultSet rs;
    public void connect(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            condb = DriverManager.getConnection("jdbc:mysql://localhost:3306/users","root","");
        }
        catch(ClassNotFoundException | SQLException e){
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        LOGIN = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        User_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        Pass_field = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        REGISTER = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fname_f = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lname_f = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        age_f = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bday_f = new com.toedter.calendar.JDateChooser();
        gender_f = new javax.swing.JComboBox<>();
        status_f = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        id_f = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        usr_f = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pass_f = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        try_p = new javax.swing.JPasswordField();
        register_button = new javax.swing.JButton();
        SEARCH = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        id_field = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        fname_field = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lname_field = new javax.swing.JTextField();
        age_field = new javax.swing.JTextField();
        bday_field = new javax.swing.JTextField();
        gender_field = new javax.swing.JTextField();
        userf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        delete_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        stat = new javax.swing.JTextField();
        clear_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(75, 68, 83));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(75, 68, 83));
        jButton1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 76, -1));

        jButton2.setBackground(new java.awt.Color(75, 68, 83));
        jButton2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Register");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 76, -1));

        jButton3.setBackground(new java.awt.Color(75, 68, 83));
        jButton3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Search");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 76, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo3.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 380));

        LOGIN.setBackground(new java.awt.Color(129, 90, 114));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Name");

        User_field.setBackground(new java.awt.Color(251, 234, 255));
        User_field.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        User_field.setForeground(new java.awt.Color(75, 68, 83));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");

        login_button.setBackground(new java.awt.Color(75, 68, 83));
        login_button.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        Pass_field.setBackground(new java.awt.Color(251, 234, 255));
        Pass_field.setForeground(new java.awt.Color(129, 90, 114));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 234, 255));
        jLabel1.setText("Forgot Password ?");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LOGINLayout = new javax.swing.GroupLayout(LOGIN);
        LOGIN.setLayout(LOGINLayout);
        LOGINLayout.setHorizontalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LOGINLayout.createSequentialGroup()
                        .addComponent(login_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(User_field)
                    .addComponent(Pass_field))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        LOGINLayout.setVerticalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(User_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LOGINLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(login_button))
                    .addGroup(LOGINLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", LOGIN);

        REGISTER.setBackground(new java.awt.Color(129, 90, 114));
        REGISTER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        REGISTER.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 83, -1, -1));

        fname_f.setBackground(new java.awt.Color(251, 234, 255));
        fname_f.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        fname_f.setForeground(new java.awt.Color(75, 68, 83));
        REGISTER.add(fname_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 82, 145, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");
        REGISTER.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 112, -1, -1));

        lname_f.setBackground(new java.awt.Color(251, 234, 255));
        lname_f.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        lname_f.setForeground(new java.awt.Color(75, 68, 83));
        REGISTER.add(lname_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 111, 145, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Age");
        REGISTER.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        age_f.setBackground(new java.awt.Color(251, 234, 255));
        age_f.setEditable(true);
        age_f.setMaximumRowCount(5);
        age_f.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        age_f.setSelectedItem("");
        age_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_fActionPerformed(evt);
            }
        });
        REGISTER.add(age_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 49, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        REGISTER.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status");
        REGISTER.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Birthday");
        REGISTER.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));
        REGISTER.add(bday_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 136, -1));

        gender_f.setBackground(new java.awt.Color(251, 234, 255));
        gender_f.setEditable(true);
        gender_f.setMaximumRowCount(2);
        gender_f.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        gender_f.setSelectedItem("");
        gender_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_fActionPerformed(evt);
            }
        });
        REGISTER.add(gender_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        status_f.setBackground(new java.awt.Color(251, 234, 255));
        status_f.setEditable(true);
        status_f.setMaximumRowCount(4);
        status_f.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Widowed" }));
        status_f.setSelectedItem("");
        status_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_fActionPerformed(evt);
            }
        });
        REGISTER.add(status_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Create  ID");
        REGISTER.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        id_f.setBackground(new java.awt.Color(251, 234, 255));
        id_f.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        id_f.setForeground(new java.awt.Color(75, 68, 83));
        REGISTER.add(id_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 100, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Create  User Name");
        REGISTER.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        usr_f.setBackground(new java.awt.Color(251, 234, 255));
        usr_f.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        usr_f.setForeground(new java.awt.Color(75, 68, 83));
        REGISTER.add(usr_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 141, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Create  Password");
        REGISTER.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        pass_f.setBackground(new java.awt.Color(251, 234, 255));
        REGISTER.add(pass_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 141, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Confirm  Password");
        REGISTER.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        try_p.setBackground(new java.awt.Color(251, 234, 255));
        REGISTER.add(try_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 141, -1));

        register_button.setBackground(new java.awt.Color(75, 68, 83));
        register_button.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        register_button.setForeground(new java.awt.Color(255, 255, 255));
        register_button.setText("Register");
        register_button.setBorderPainted(false);
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });
        REGISTER.add(register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jTabbedPane1.addTab("tab2", REGISTER);

        SEARCH.setBackground(new java.awt.Color(129, 90, 114));
        SEARCH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        SEARCH.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 157, -1, -1));

        id_field.setBackground(new java.awt.Color(251, 234, 255));
        id_field.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        id_field.setForeground(new java.awt.Color(75, 68, 83));
        SEARCH.add(id_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 41, 136, -1));

        jButton4.setBackground(new java.awt.Color(75, 68, 83));
        jButton4.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Find");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        SEARCH.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 76, 57, -1));
        SEARCH.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 112, 471, 10));

        jLabel15.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Input Student ID");
        SEARCH.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 42, -1, -1));

        fname_field.setBackground(new java.awt.Color(251, 234, 255));
        fname_field.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        fname_field.setForeground(new java.awt.Color(75, 68, 83));
        SEARCH.add(fname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 156, 136, -1));

        jLabel16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Last Name");
        SEARCH.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 195, -1, -1));

        lname_field.setBackground(new java.awt.Color(251, 234, 255));
        lname_field.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        lname_field.setForeground(new java.awt.Color(75, 68, 83));
        SEARCH.add(lname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 194, 136, -1));

        age_field.setBackground(new java.awt.Color(251, 234, 255));
        age_field.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        age_field.setForeground(new java.awt.Color(75, 68, 83));
        SEARCH.add(age_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 235, 136, -1));

        bday_field.setBackground(new java.awt.Color(251, 234, 255));
        bday_field.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        bday_field.setForeground(new java.awt.Color(75, 68, 83));
        SEARCH.add(bday_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 156, 136, -1));

        gender_field.setBackground(new java.awt.Color(251, 234, 255));
        gender_field.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        gender_field.setForeground(new java.awt.Color(75, 68, 83));
        SEARCH.add(gender_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 270, 136, -1));

        userf.setBackground(new java.awt.Color(251, 234, 255));
        userf.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        userf.setForeground(new java.awt.Color(75, 68, 83));
        SEARCH.add(userf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 136, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Age");
        SEARCH.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 236, -1, -1));

        jLabel18.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Gender");
        SEARCH.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 271, -1, -1));

        jLabel19.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Birthday");
        SEARCH.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 157, -1, -1));

        jLabel20.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Status");
        SEARCH.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 195, -1, -1));

        delete_button.setBackground(new java.awt.Color(75, 68, 83));
        delete_button.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        delete_button.setForeground(new java.awt.Color(255, 255, 255));
        delete_button.setText("Delete");
        delete_button.setBorderPainted(false);
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });
        SEARCH.add(delete_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        update_button.setBackground(new java.awt.Color(75, 68, 83));
        update_button.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        update_button.setForeground(new java.awt.Color(255, 255, 255));
        update_button.setText("Update");
        update_button.setBorderPainted(false);
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        SEARCH.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        jLabel21.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("User Name");
        SEARCH.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        stat.setBackground(new java.awt.Color(251, 234, 255));
        stat.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        stat.setForeground(new java.awt.Color(75, 68, 83));
        SEARCH.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 194, 136, -1));

        clear_button1.setBackground(new java.awt.Color(75, 68, 83));
        clear_button1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        clear_button1.setForeground(new java.awt.Color(255, 255, 255));
        clear_button1.setText("Clear");
        clear_button1.setBorderPainted(false);
        clear_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_button1ActionPerformed(evt);
            }
        });
        SEARCH.add(clear_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        jTabbedPane1.addTab("tab3", SEARCH);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, -30, 530, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        
        //String student_id = Id_field.getText();
        String user = User_field.getText();
        String pass = Pass_field.getText();
        
        try{
            
            Statement state = condb.createStatement();
            rs = state.executeQuery("SELECT * FROM student WHERE username = '"+ user + "'and pass = '"+ pass + "'");
           
            String getUsername = "";
            String getPassword = "";
            //String getID = "";
            if(rs.next()){
                 getUsername = rs.getString("username");
                 getPassword = rs.getString("pass");
                 //getID = rs.getString("studentID");
            }
                /*if(student_id.equals(getID) && user.equals(getUsername) && pass.equals(getPassword)){
                    JOptionPane.showMessageDialog(null,"LOG-IN SUCCESSFUL");
                }*/
            if(user.equals("") && pass.equals("")){
                JOptionPane.showMessageDialog(null, "Enter Username or Password","Error",JOptionPane.ERROR_MESSAGE);
                 }
            else if(user.equals(getUsername) && pass.equals(getPassword)){
               /* Info page = new Info();//Info: name of the other GUI
                page.setVisible(true);
                setVisible(false);// Current Page*/
               JOptionPane.showMessageDialog(null,"LOG-IN SUCCESSFUL");
               User_field.setText("");
               Pass_field.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid Username or Password","Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(Exception e){
            //e
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void age_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_fActionPerformed

    private void gender_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_fActionPerformed

    private void status_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_fActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO add your handling code here:
         try{
            String query = "INSERT INTO `student`(`studentID`, `fname`, `lname`, `age`, `gender`, `bday`, `status`, `username`, `pass`) VALUES (?,?,?,?,?,?,?,?,?)";
            //condb = DriverManager.getConnection("jdbc:mysql://localhost:3306/users","root","");
            pst = condb.prepareStatement(query);
            pst.setString(1, id_f.getText());
            pst.setString(2, fname_f.getText());
            pst.setString(3, lname_f.getText());
            pst.setString(4, age_f.getSelectedItem().toString());
            pst.setString(5, gender_f.getSelectedItem().toString());
            
           // SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy- -dd");
           // pst.setString(6, dateFormat.format(bday_f.getDate()));
            //pst.setString(6,bday_f.getDate().toString());
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            pst.setString(6, formatter.format(bday_f.getDate()));
            pst.setString(7, status_f.getSelectedItem().toString());
            pst.setString(8, usr_f.getText());
            String try1 = pass_f.getText();
            String try2 = try_p.getText();
            String usrname = usr_f.getText();
            String fname = fname_f.getText();
            String lname = lname_f.getText();
            String id = id_f.getText();
            String age = age_f.getSelectedItem().toString();
            String gender =gender_f.getSelectedItem().toString();
            //String bday = bday_f.getDate().toString();
            String bday = formatter.format(bday_f.getDate());
            String status = status_f.getSelectedItem().toString();
            
            if(usrname.equals("")){
                JOptionPane.showMessageDialog(null, "Please Enter Username","Error",JOptionPane.ERROR_MESSAGE);
            } 
            if(fname.equals("")||lname.equals("")){
                JOptionPane.showMessageDialog(null, "Please Enter first name or last name","Error",JOptionPane.ERROR_MESSAGE);
            }
            if(id.equals("")){
                JOptionPane.showMessageDialog(null, "Please Enter id","Error",JOptionPane.ERROR_MESSAGE);
            }
            if(age.equals("")){
                JOptionPane.showMessageDialog(null, "Please Enter your Age","Error",JOptionPane.ERROR_MESSAGE);
            }
            if(gender.equals("")){
                JOptionPane.showMessageDialog(null, "Please Choose your Gender","Error",JOptionPane.ERROR_MESSAGE);
            }
            if(bday.equals("")){
                JOptionPane.showMessageDialog(null, "Please Enter your Birth Day","Error",JOptionPane.ERROR_MESSAGE);
            }
            if(status.equals("")){
                JOptionPane.showMessageDialog(null, "Please choose your Status","Error",JOptionPane.ERROR_MESSAGE);
            }
            if(try2.equals(try1)){
                pst.setString(9, pass_f.getText());
            }
            else {
                JOptionPane.showMessageDialog(null, "password not matched!","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "You Are Now Registered!");
            
           
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_register_buttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String studID = id_field.getText();
        try{
            //String getID = rs.getString("studentID");
            pst = condb.prepareStatement("SELECT * FROM student Where studentID=?");
            pst.setString(1,studID );
            rs = pst.executeQuery();
            if(rs.next()){
                id_field.setText(rs.getString("studentID"));
                fname_field.setText(rs.getString("fname"));
                lname_field.setText(rs.getString("lname"));
                age_field.setText(rs.getString("age"));
                gender_field.setText(rs.getString("gender"));
                bday_field.setText(rs.getString("bday"));
                stat.setText(rs.getString("status"));
                userf.setText(rs.getString("username"));
            }
            else{
                JOptionPane.showMessageDialog(null,"Sorry Record Not Founf","Error",JOptionPane.ERROR_MESSAGE);
                id_field.setText("");
                fname_field.setText("");
                lname_field.setText("");
                age_field.setText("");
                gender_field.setText("");
                bday_field.setText("");
                stat.setText("");
                userf.setText("");
            }
        }
        catch(Exception e){
            //e
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
            // TODO add your handling code here:
        forgot page = new forgot();
        page.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
         int answer;
        answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this record?","System Message",JOptionPane.YES_NO_OPTION);
        if(answer==JOptionPane.YES_OPTION){
            try {
            
            Statement state = condb.createStatement();
            state.executeUpdate("UPDATE student SET  username= '"+userf.getText()+"',fname= '"+fname_field.getText()+"',lname= '"+lname_field.getText()+"',age= '"+age_field.getText()+"', bday= '"+bday_field.getText()+"',gender= '"+gender_field.getText()+"',status = '"+userf.getText()+"'Where studentID = '"+id_field.getText()+"' ");

                String query;
                query = "Delete From student Where studentID='" + id_field.getText() + "'";
                state.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Record Deleted","System Message",JOptionPane.INFORMATION_MESSAGE);
                 fname_field.setText("");
                 lname_field.setText("");
                 age_field.setText("");
                 bday_field.setText("");
                 userf.setText("");
                 gender_field.setText("");
                 userf.setText("");
                 id_field.setText("");
                 stat.setText("");
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        int answer;
        answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this record?","System Message",
                JOptionPane.YES_NO_OPTION);
        if(answer==JOptionPane.YES_OPTION){
       
            try {
                delete_button.setEnabled(false);
           
            Statement state = condb.createStatement();
            state.executeUpdate("UPDATE student SET  username= '"+userf.getText()+"',fname= '"+fname_field.getText()+"',lname= '"+lname_field.getText()+"',age= '"+age_field.getText()+"', bday= '"+bday_field.getText()+"',gender= '"+gender_field.getText()+"',status = '"+userf.getText()+"'Where studentID = '"+id_field.getText()+"' ");
            JOptionPane.showMessageDialog(null, "Record Updated","System Message",JOptionPane.INFORMATION_MESSAGE);
            
                 fname_field.setText("");
                 lname_field.setText("");
                 age_field.setText("");
                 bday_field.setText("");
                 userf.setText("");
                 gender_field.setText("");
                 userf.setText("");
                 id_field.setText("");
                 stat.setText("");
                 delete_button.setEnabled(true);
           
        } //Logger.getLogger(frameTerminateEdit.class.getName()).log(Level.SEVERE, null, ex);
            catch (SQLException ex) {
            //Logger.getLogger(frameTerminateEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void clear_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_button1ActionPerformed
        // TODO add your handling code here:
        try{
            fname_field.setText("");
            lname_field.setText("");
            age_field.setText("");
            bday_field.setText("");
            userf.setText("");
            gender_field.setText("");
            userf.setText("");
            id_field.setText("");
            stat.setText("");
        }
        catch(Exception e){
                 
        }
    }//GEN-LAST:event_clear_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CRUD().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LOGIN;
    private javax.swing.JPasswordField Pass_field;
    private javax.swing.JPanel REGISTER;
    private javax.swing.JPanel SEARCH;
    private javax.swing.JTextField User_field;
    private javax.swing.JComboBox<String> age_f;
    private javax.swing.JTextField age_field;
    private com.toedter.calendar.JDateChooser bday_f;
    private javax.swing.JTextField bday_field;
    private javax.swing.JButton clear_button1;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField fname_f;
    private javax.swing.JTextField fname_field;
    private javax.swing.JComboBox<String> gender_f;
    private javax.swing.JTextField gender_field;
    private javax.swing.JTextField id_f;
    private javax.swing.JTextField id_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lname_f;
    private javax.swing.JTextField lname_field;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField pass_f;
    private javax.swing.JButton register_button;
    private javax.swing.JTextField stat;
    private javax.swing.JComboBox<String> status_f;
    private javax.swing.JPasswordField try_p;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField userf;
    private javax.swing.JTextField usr_f;
    // End of variables declaration//GEN-END:variables
}
